# Generated by Django 3.0.6 on 2020-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peddidos',
            new_name='Pedidos',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='precion',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
